version: '3.8'
services:
  trilux-app:
    build: .
    container_name: trilux-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/app/ssl
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433; Initial Catalog=AppDbContext; User ID=SA;Password=Password123;Encrypt=True;TrustServerCertificate=True
    restart: always
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: trilux-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y" 
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  sql_data: